### ISSUE TITLE
使用指令报错，转换CQ码错误

### ISSUE THREAD

**Issue by Aobaaaa** [evan-gyy/zhenxun_bot_plugins#1]
你好 我使用莲莲骂人和汉奸等一些指令会报错，随机莲莲的部分图片和爱国指令没有问题，请问是怎么回事
![HQ9`ZQ_JI0Z@8S~$2RECSET](https://user-images.githubusercontent.com/106361074/196026829-c00efc26-7bfb-4592-bd23-3325e42ba982.png)

**Comment by evan-gyy** [comment]
您好，错误原因应该是未安装ffmpeg，所以无法转换音频文件，请安装ffmpeg并添加到环境变量，然后重启bot

**Comment by Aobaaaa** [comment]
> 您好，错误原因应该是未安装ffmpeg，所以无法转换音频文件，请安装ffmpeg并添加到环境变量，然后重启bot

问题已解决 感谢！
