### ISSUE TITLE
aiArt插件显示创作者密匙不存在

### ISSUE THREAD

**Issue by season9** [evan-gyy/zhenxun_bot_plugins#3]
![image](https://user-images.githubusercontent.com/94514278/215309132-b675de4b-6e07-4aba-8846-7dfa0281a917.png)

![image](https://user-images.githubusercontent.com/94514278/215309174-d0b1dbf5-0859-4bd0-bc1a-fc54fbce34b8.png)

我输进去了 显示密匙不存在

**Comment by season9** [comment]
不知为啥 把两个key写在下面源码处就好了

**Comment by evan-gyy** [comment]
因为他是按列表方式读取的，如果只放一组密钥可以这样：
```
API_KEY = ["YourAPIKEY"]
SECRET_KEY = ["YourSECRETKEY"]
```
